# fly.toml file generated for backend2323 on 2022-12-13T17:27:54-08:00

app = "backend2323"
kill_signal = "SIGINT"
kill_timeout = 5


[env]
  PORT = "8000"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000

  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"


[deploy]
  release_command = "python manage.py migrate --noinput"