# Generated by Django 4.1.1 on 2022-10-12 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_answer_answer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='person',
        ),
    ]
