# Generated by Django 4.1.1 on 2022-10-12 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_quizzes_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.person'),
        ),
    ]
