# Generated by Django 4.1.1 on 2022-10-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_answer_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.IntegerField(blank=True, verbose_name='Answer'),
        ),
    ]
