# Generated by Django 4.1.1 on 2022-10-12 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_answer_answer_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_text',
            new_name='answer',
        ),
    ]
