# Generated by Django 4.1.1 on 2022-10-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_answer_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user_email',
            field=models.EmailField(blank=True, max_length=70, unique=True),
        ),
    ]
