# Generated by Django 4.1.1 on 2022-10-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_person_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user_email',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
