# Generated by Django 4.1.1 on 2022-10-19 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_answer_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.person'),
        ),
    ]
