# Generated by Django 4.1.1 on 2022-10-19 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_quizzes_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlikert',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='api.quizzes'),
        ),
    ]
