# Generated by Django 4.1.4 on 2022-12-15 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rankingname_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingname',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.person'),
        ),
    ]
