# Generated by Django 4.1.4 on 2022-12-15 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_rankingname_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer', to='api.questionlikert'),
        ),
        migrations.RemoveField(
            model_name='choice',
            name='rankingName',
        ),
        migrations.AddField(
            model_name='choice',
            name='rankingName',
            field=models.ManyToManyField(to='api.rankingname'),
        ),
    ]
