# Generated by Django 4.1.4 on 2022-12-15 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_answer_question_remove_choice_rankingname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingname',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RankingName', to='api.person'),
        ),
    ]
