# Generated by Django 4.1.4 on 2022-12-15 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_answer_question_alter_questionlikert_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Quizzes', to='api.person'),
        ),
    ]
