# Generated by Django 4.1.4 on 2022-12-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_quizzes_person_quizzes_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='quizzes',
            field=models.ManyToManyField(to='api.quizzes'),
        ),
    ]
