# Generated by Django 4.1.4 on 2022-12-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_quizzes_person_person_quizzes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='rankingName',
            field=models.ManyToManyField(related_name='rankingName', to='api.rankingname'),
        ),
    ]
