# Generated by Django 4.1.4 on 2022-12-16 00:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_choice_rankingname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='rankingName',
        ),
        migrations.RemoveField(
            model_name='rankingname',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='rankingname',
            name='person',
        ),
        migrations.RemoveField(
            model_name='rankingname',
            name='title',
        ),
        migrations.AddField(
            model_name='choice',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Choice', to='api.person'),
        ),
        migrations.AddField(
            model_name='choice',
            name='title',
            field=models.CharField(default='New Choice', max_length=255, verbose_name='Ranking Title'),
        ),
        migrations.AddField(
            model_name='rankingname',
            name='choice',
            field=models.ManyToManyField(related_name='choice', to='api.choice'),
        ),
        migrations.AddField(
            model_name='rankingname',
            name='rankingName',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='RankingName'),
            preserve_default=False,
        ),
    ]
