# Generated by Django 4.1.4 on 2022-12-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_choice_choice_remove_choice_rankingname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingname',
            name='choice',
            field=models.ManyToManyField(blank=True, null=True, related_name='choice', to='api.choice'),
        ),
    ]
