# Generated by Django 4.1.4 on 2022-12-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_rankingname_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Choice title'),
        ),
        migrations.AlterField(
            model_name='person',
            name='quizzes',
            field=models.ManyToManyField(blank=True, null=True, to='api.quizzes'),
        ),
        migrations.AlterField(
            model_name='rankingname',
            name='choice',
            field=models.ManyToManyField(blank=True, related_name='choice', to='api.choice'),
        ),
        migrations.CreateModel(
            name='RankingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('userChoice', models.IntegerField(blank=True, verbose_name='RankingAnswer')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rankingAnswer', to='api.choice')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.person')),
            ],
            options={
                'verbose_name': 'RankingAnswer',
                'verbose_name_plural': 'RankingAnswers',
                'ordering': ['id'],
            },
        ),
    ]
