# Generated by Django 4.1.4 on 2022-12-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_choice_title_alter_person_quizzes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='rankingName',
            field=models.ManyToManyField(blank=True, to='api.rankingname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='quizzes',
            field=models.ManyToManyField(blank=True, to='api.quizzes'),
        ),
    ]
