# Generated by Django 4.1.4 on 2022-12-16 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_choice_person_person_rankingname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankingname',
            name='choice',
        ),
        migrations.AddField(
            model_name='rankingname',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='api.choice'),
        ),
    ]
