# Generated by Django 4.1.4 on 2022-12-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_rankingname_choice_rankingname_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankingname',
            name='choice',
        ),
        migrations.AddField(
            model_name='rankingname',
            name='choice',
            field=models.ManyToManyField(blank=True, related_name='choice', to='api.choice'),
        ),
    ]
