# Generated by Django 4.1.4 on 2022-12-21 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_rankingname_choice_rankingname_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankinganswer',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rankingAnswer', to='api.choice'),
        ),
    ]
