# Generated by Django 4.1.4 on 2022-12-21 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_rankinganswer_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankinganswer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rankingAnswer', to='api.choice'),
        ),
        migrations.AlterField(
            model_name='rankinganswer',
            name='userChoice',
            field=models.IntegerField(blank=True, null=True, verbose_name='RankingAnswer'),
        ),
    ]
